CREATE USER IF NOT EXISTS 'bearfax'@'%' IDENTIFIED BY 'SE_KOPW$tw90eu93~233';
CREATE USER IF NOT EXISTS 'bearfax'@'localhost' IDENTIFIED BY 'SE_KOPW$tw90eu93~233';

CREATE SCHEMA IF NOT EXISTS bearfax DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT ALL PRIVILEGES ON bearfax.* TO 'bearfax'@'%';
GRANT ALL PRIVILEGES ON bearfax.* TO 'bearfax'@'localhost';

FLUSH PRIVILEGES;
